##
## Plugin config template.
## This template file is manually curated for the particular OSA version
##
pluginVersion: v5.0
## Openshift component logging levels
componentLogLevel:
  apiServer: 2
  controllerManager: 2
  node: 5
## Change this for an address range using CIDR notation (e.g. 192.168.99.0/24); an IP address (e.g. 192.168.99.0);
## or a list of address ranges or IP addresses (e.g. 192.168.99.0/24,10.0.0.0/24,44.66.0.0/24)
## having access to system nodes: default (any ip address)
sshSourceAddressPrefixes: ['0.0.0.0/0']
versions:
  v3.2:
    ## Node image and version configurables
    imageOffer: osa
    imagePublisher: redhat
    imageSku: osa_311
    imageVersion: 311.82.20190311
    images:
      alertManager: registry.access.redhat.com/openshift3/prometheus-alertmanager:v3.11.82
      ansibleServiceBroker: registry.access.redhat.com/openshift3/ose-ansible-service-broker:v3.11.82
      clusterMonitoringOperator: registry.access.redhat.com/openshift3/ose-cluster-monitoring-operator:v3.11.82
      configReloader: registry.access.redhat.com/openshift3/ose-configmap-reloader:v3.11.82
      console: registry.access.redhat.com/openshift3/ose-console:v3.11.82
      controlPlane: registry.access.redhat.com/openshift3/ose-control-plane:v3.11.82
      grafana: registry.access.redhat.com/openshift3/grafana:v3.11.82
      kubeRbacProxy: registry.access.redhat.com/openshift3/ose-kube-rbac-proxy:v3.11.82
      kubeStateMetrics: registry.access.redhat.com/openshift3/ose-kube-state-metrics:v3.11.82
      node: registry.access.redhat.com/openshift3/ose-node:v3.11.82
      nodeExporter: registry.access.redhat.com/openshift3/prometheus-node-exporter:v3.11.82
      oAuthProxy: registry.access.redhat.com/openshift3/oauth-proxy:v3.11.82
      prometheus: registry.access.redhat.com/openshift3/prometheus:v3.11.82
      prometheusConfigReloader: registry.access.redhat.com/openshift3/ose-prometheus-config-reloader:v3.11.82
      prometheusOperator: registry.access.redhat.com/openshift3/ose-prometheus-operator:v3.11.82
      registry: registry.access.redhat.com/openshift3/ose-docker-registry:v3.11.82
      registryConsole: registry.access.redhat.com/openshift3/registry-console:v3.11.82
      router: registry.access.redhat.com/openshift3/ose-haproxy-router:v3.11.82
      serviceCatalog: registry.access.redhat.com/openshift3/ose-service-catalog:v3.11.82
      templateServiceBroker: registry.access.redhat.com/openshift3/ose-template-service-broker:v3.11.82
      webConsole: registry.access.redhat.com/openshift3/ose-web-console:v3.11.82
      format: registry.access.redhat.com/openshift3/ose-${component}:${version}
      httpd: registry.access.redhat.com/rhscl/httpd-24-rhel7:2.4-85
      masterEtcd: registry.access.redhat.com/rhel7/etcd:3.2.22
      genevaLogging: osarpint.azurecr.io/acs/mdsd:master.20190228.1
      genevaStatsd: osarpint.azurecr.io/acs/mdm:git-a909a2e76
      genevaTDAgent: osarpint.azurecr.io/acs/td-agent:master.20190228.1
      azureControllers: quay.io/openshift-on-azure/azure-controllers:v3.2
      etcdBackup: quay.io/openshift-on-azure/etcdbackup:v3.2
      metricsBridge: quay.io/openshift-on-azure/metricsbridge:v3.2
      startup: quay.io/openshift-on-azure/startup:v3.2
      sync: quay.io/openshift-on-azure/sync:v3.2
      tlsProxy: quay.io/openshift-on-azure/tlsproxy:v3.2
  v4.0:
    ## Node image and version configurables
    imageOffer: osa
    imagePublisher: redhat
    imageSku: osa_311
    imageVersion: 311.88.20190322
    images:
      alertManager: registry.access.redhat.com/openshift3/prometheus-alertmanager:v3.11.88
      ansibleServiceBroker: registry.access.redhat.com/openshift3/ose-ansible-service-broker:v3.11.88
      clusterMonitoringOperator: registry.access.redhat.com/openshift3/ose-cluster-monitoring-operator:v3.11.88
      configReloader: registry.access.redhat.com/openshift3/ose-configmap-reloader:v3.11.88
      console: registry.access.redhat.com/openshift3/ose-console:v3.11.88
      controlPlane: registry.access.redhat.com/openshift3/ose-control-plane:v3.11.88
      grafana: registry.access.redhat.com/openshift3/grafana:v3.11.88
      kubeRbacProxy: registry.access.redhat.com/openshift3/ose-kube-rbac-proxy:v3.11.88
      kubeStateMetrics: registry.access.redhat.com/openshift3/ose-kube-state-metrics:v3.11.88
      node: registry.access.redhat.com/openshift3/ose-node:v3.11.88
      nodeExporter: registry.access.redhat.com/openshift3/prometheus-node-exporter:v3.11.88
      oAuthProxy: registry.access.redhat.com/openshift3/oauth-proxy:v3.11.88
      prometheus: registry.access.redhat.com/openshift3/prometheus:v3.11.88
      prometheusConfigReloader: registry.access.redhat.com/openshift3/ose-prometheus-config-reloader:v3.11.88
      prometheusOperator: registry.access.redhat.com/openshift3/ose-prometheus-operator:v3.11.88
      registry: registry.access.redhat.com/openshift3/ose-docker-registry:v3.11.88
      registryConsole: registry.access.redhat.com/openshift3/registry-console:v3.11.88
      router: registry.access.redhat.com/openshift3/ose-haproxy-router:v3.11.88
      serviceCatalog: registry.access.redhat.com/openshift3/ose-service-catalog:v3.11.88
      templateServiceBroker: registry.access.redhat.com/openshift3/ose-template-service-broker:v3.11.88
      webConsole: registry.access.redhat.com/openshift3/ose-web-console:v3.11.88
      format: registry.access.redhat.com/openshift3/ose-${component}:v3.11.88
      httpd: registry.access.redhat.com/rhscl/httpd-24-rhel7:2.4-85
      masterEtcd: registry.access.redhat.com/rhel7/etcd:3.2.22
      genevaLogging: osarpint.azurecr.io/acs/mdsd:master.20190228.1
      genevaStatsd: osarpint.azurecr.io/acs/mdm:git-a909a2e76
      genevaTDAgent: osarpint.azurecr.io/acs/td-agent:master.20190228.1
      azureControllers: quay.io/openshift-on-azure/azure-controllers:latest
      canary: quay.io/openshift-on-azure/canary:latest
      etcdBackup: quay.io/openshift-on-azure/etcdbackup:latest
      metricsBridge: quay.io/openshift-on-azure/metricsbridge:latest
      startup: quay.io/openshift-on-azure/startup:latest
      sync: quay.io/openshift-on-azure/sync:latest
      tlsProxy: quay.io/openshift-on-azure/tlsproxy:latest
  v5.0:
    ## Node image and version configurables
    imageOffer: osa
    imagePublisher: redhat
    imageSku: osa_311
    imageVersion: 311.88.20190322
    images:
      alertManager: registry.access.redhat.com/openshift3/prometheus-alertmanager:v3.11.88
      ansibleServiceBroker: registry.access.redhat.com/openshift3/ose-ansible-service-broker:v3.11.88
      clusterMonitoringOperator: registry.access.redhat.com/openshift3/ose-cluster-monitoring-operator:v3.11.88
      configReloader: registry.access.redhat.com/openshift3/ose-configmap-reloader:v3.11.88
      console: registry.access.redhat.com/openshift3/ose-console:v3.11.88
      controlPlane: registry.access.redhat.com/openshift3/ose-control-plane:v3.11.88
      grafana: registry.access.redhat.com/openshift3/grafana:v3.11.88
      kubeRbacProxy: registry.access.redhat.com/openshift3/ose-kube-rbac-proxy:v3.11.88
      kubeStateMetrics: registry.access.redhat.com/openshift3/ose-kube-state-metrics:v3.11.88
      node: registry.access.redhat.com/openshift3/ose-node:v3.11.88
      nodeExporter: registry.access.redhat.com/openshift3/prometheus-node-exporter:v3.11.88
      oAuthProxy: registry.access.redhat.com/openshift3/oauth-proxy:v3.11.88
      prometheus: registry.access.redhat.com/openshift3/prometheus:v3.11.88
      prometheusConfigReloader: registry.access.redhat.com/openshift3/ose-prometheus-config-reloader:v3.11.88
      prometheusOperator: registry.access.redhat.com/openshift3/ose-prometheus-operator:v3.11.88
      registry: registry.access.redhat.com/openshift3/ose-docker-registry:v3.11.88
      registryConsole: registry.access.redhat.com/openshift3/registry-console:v3.11.88
      router: registry.access.redhat.com/openshift3/ose-haproxy-router:v3.11.88
      serviceCatalog: registry.access.redhat.com/openshift3/ose-service-catalog:v3.11.88
      templateServiceBroker: registry.access.redhat.com/openshift3/ose-template-service-broker:v3.11.88
      webConsole: registry.access.redhat.com/openshift3/ose-web-console:v3.11.88
      format: registry.access.redhat.com/openshift3/ose-${component}:v3.11.88
      httpd: registry.access.redhat.com/rhscl/httpd-24-rhel7:2.4-85
      masterEtcd: registry.access.redhat.com/rhel7/etcd:3.2.22
      genevaLogging: osarpint.azurecr.io/acs/mdsd:master.20190228.1
      genevaStatsd: osarpint.azurecr.io/acs/mdm:git-a909a2e76
      genevaTDAgent: osarpint.azurecr.io/acs/td-agent:master.20190228.1
      azureControllers: quay.io/openshift-on-azure/azure-controllers:latest
      canary: quay.io/openshift-on-azure/canary:latest
      etcdBackup: quay.io/openshift-on-azure/etcdbackup:latest
      metricsBridge: quay.io/openshift-on-azure/metricsbridge:latest
      startup: quay.io/openshift-on-azure/startup:latest
      sync: quay.io/openshift-on-azure/sync:latest
      tlsProxy: quay.io/openshift-on-azure/tlsproxy:latest
## certificates, used to authenticate to external systems
## Geneva integration certificates. Example:
#certificates:
  #genevaLogging:
  #  key: <Geneva logging key value. Format: Base64 in YAML, rsa.PrivateKey in struct>
  #  cert: <Geneva logging certificate Format: Base64 in YAML, x509.Certificate struct>
  #genevaMetrics:
  #  key: <Geneva metrics key value. Base64 in YAML, rsa.PrivateKey in struct>
  #  cert: <Geneva metrics certificate value. Format: Base64 in YAML, x509.Certificate struct>
## Geneva integration other details
genevaLoggingSector: US-Test
genevaLoggingAccount: ccpopenshiftdiag
genevaLoggingNamespace: CCPOpenShift
genevaLoggingControlPlaneAccount: RPOpenShiftAccount
genevaLoggingControlPlaneEnvironment: Test
genevaLoggingControlPlaneRegion: eastus
genevaMetricsAccount: RPOpenShift
genevaMetricsEndpoint: https://az-int.metrics.nsatc.net/
## Container images used for specific OSA Cluster version
## Geneva image pull secret is used to access private component images. Format: base64 encoded .docker/config.json file "{auths:{osarpint.azurecr.io:{username:username,password:notthepasswordyouarelookingfor,email:openshift@example.com,auth:dXNlcm5hbWU6bm90dGhlcGFzc3dvcmR5b3VhcmVsb29raW5nZm9yCg==}}}"
#genevaImagePullSecret: <base64 string of .docker/config.json file>
## Image pull secret is used to pull images from private registries, used system-wide
#imagePullSecret: <base64 string of /var/lib/origin/.docker/config.json file>
