##
## Plugin config template.
## This template file is manually curated for the particular OSA version
##
pluginVersion: v9.0
## List of RPM packages that fix security issues
securityPatchPackages: []
## Openshift component logging levels
componentLogLevel:
  apiServer: 2
  controllerManager: 2
  node: 2
## Change this for an address range using CIDR notation (e.g. 192.168.99.0/24); an IP address (e.g. 192.168.99.0);
## or a list of address ranges or IP addresses (e.g. 192.168.99.0/24,10.0.0.0/24,44.66.0.0/24)
## having access to system nodes: default (any ip address)
sshSourceAddressPrefixes: ['0.0.0.0/0']
versions:
  v7.0:
    imageOffer: osa
    imagePublisher: redhat
    imageSku: osa_311
    imageVersion: 311.129.20190810
    images:
      alertManager: registry.access.redhat.com/openshift3/prometheus-alertmanager:v3.11.129
      ansibleServiceBroker: registry.access.redhat.com/openshift3/ose-ansible-service-broker:v3.11.129
      clusterMonitoringOperator: registry.access.redhat.com/openshift3/ose-cluster-monitoring-operator:v3.11.129
      configReloader: registry.access.redhat.com/openshift3/ose-configmap-reloader:v3.11.129
      console: registry.access.redhat.com/openshift3/ose-console:v3.11.129
      controlPlane: registry.access.redhat.com/openshift3/ose-control-plane:v3.11.129
      grafana: registry.access.redhat.com/openshift3/grafana:v3.11.129
      kubeRbacProxy: registry.access.redhat.com/openshift3/ose-kube-rbac-proxy:v3.11.129
      kubeStateMetrics: registry.access.redhat.com/openshift3/ose-kube-state-metrics:v3.11.129
      node: registry.access.redhat.com/openshift3/ose-node:v3.11.129
      nodeExporter: registry.access.redhat.com/openshift3/prometheus-node-exporter:v3.11.129
      oAuthProxy: registry.access.redhat.com/openshift3/oauth-proxy:v3.11.129
      prometheus: registry.access.redhat.com/openshift3/prometheus:v3.11.129
      prometheusConfigReloader: registry.access.redhat.com/openshift3/ose-prometheus-config-reloader:v3.11.129
      prometheusOperator: registry.access.redhat.com/openshift3/ose-prometheus-operator:v3.11.129
      registry: registry.access.redhat.com/openshift3/ose-docker-registry:v3.11.129
      registryConsole: registry.access.redhat.com/openshift3/registry-console:v3.11.129
      router: registry.access.redhat.com/openshift3/ose-haproxy-router:v3.11.129
      serviceCatalog: registry.access.redhat.com/openshift3/ose-service-catalog:v3.11.129
      templateServiceBroker: registry.access.redhat.com/openshift3/ose-template-service-broker:v3.11.129
      webConsole: registry.access.redhat.com/openshift3/ose-web-console:v3.11.129
      format: registry.access.redhat.com/openshift3/ose-${component}:v3.11.129
      httpd: registry.access.redhat.com/rhscl/httpd-24-rhel7:2.4-86
      masterEtcd: registry.access.redhat.com/rhel7/etcd:3.2.22-28
      genevaLogging: osarpint.azurecr.io/acs/mdsd:master.20190228.1
      genevaStatsd: osarpint.azurecr.io/acs/mdm:git-a909a2e76
      genevaTDAgent: osarpint.azurecr.io/acs/td-agent:master.20190228.1
      azureControllers: quay.io/openshift-on-azure/azure:v7.0
      canary: quay.io/openshift-on-azure/azure:v7.0
      etcdBackup: quay.io/openshift-on-azure/azure:v7.0
      metricsBridge: quay.io/openshift-on-azure/azure:v7.0
      startup: quay.io/openshift-on-azure/azure:v7.0
      sync: quay.io/openshift-on-azure/azure:v7.0
      tlsProxy: quay.io/openshift-on-azure/azure:v7.0
      logAnalyticsAgent: mcr.microsoft.com/azuremonitor/containerinsights/ciprod:ciprod07092019
  v8.0:
    imageOffer: osa
    imagePublisher: redhat
    imageSku: osa_311
    imageVersion: 311.129.20190810
    images:
      alertManager: registry.access.redhat.com/openshift3/prometheus-alertmanager:v3.11.129
      ansibleServiceBroker: registry.access.redhat.com/openshift3/ose-ansible-service-broker:v3.11.129
      clusterMonitoringOperator: registry.access.redhat.com/openshift3/ose-cluster-monitoring-operator:v3.11.129
      configReloader: registry.access.redhat.com/openshift3/ose-configmap-reloader:v3.11.129
      console: registry.access.redhat.com/openshift3/ose-console:v3.11.129
      controlPlane: registry.access.redhat.com/openshift3/ose-control-plane:v3.11.129
      grafana: registry.access.redhat.com/openshift3/grafana:v3.11.129
      kubeRbacProxy: registry.access.redhat.com/openshift3/ose-kube-rbac-proxy:v3.11.129
      kubeStateMetrics: registry.access.redhat.com/openshift3/ose-kube-state-metrics:v3.11.129
      node: registry.access.redhat.com/openshift3/ose-node:v3.11.129
      nodeExporter: registry.access.redhat.com/openshift3/prometheus-node-exporter:v3.11.129
      oAuthProxy: registry.access.redhat.com/openshift3/oauth-proxy:v3.11.129
      prometheus: registry.access.redhat.com/openshift3/prometheus:v3.11.129
      prometheusConfigReloader: registry.access.redhat.com/openshift3/ose-prometheus-config-reloader:v3.11.129
      prometheusOperator: registry.access.redhat.com/openshift3/ose-prometheus-operator:v3.11.129
      registry: registry.access.redhat.com/openshift3/ose-docker-registry:v3.11.129
      registryConsole: registry.access.redhat.com/openshift3/registry-console:v3.11.129
      router: registry.access.redhat.com/openshift3/ose-haproxy-router:v3.11.129
      serviceCatalog: registry.access.redhat.com/openshift3/ose-service-catalog:v3.11.129
      templateServiceBroker: registry.access.redhat.com/openshift3/ose-template-service-broker:v3.11.129
      webConsole: registry.access.redhat.com/openshift3/ose-web-console:v3.11.129
      format: registry.access.redhat.com/openshift3/ose-${component}:v3.11.129
      httpd: registry.access.redhat.com/rhscl/httpd-24-rhel7:2.4-103
      masterEtcd: registry.access.redhat.com/rhel7/etcd:3.2.26-14
      genevaLogging: osarpint.azurecr.io/acs/mdsd:master.20190228.1
      genevaStatsd: osarpint.azurecr.io/acs/mdm:git-a909a2e76
      genevaTDAgent: osarpint.azurecr.io/acs/td-agent:master.20190228.1
      azureControllers: quay.io/openshift-on-azure/azure:v8.0
      canary: quay.io/openshift-on-azure/azure:v8.0
      etcdBackup: quay.io/openshift-on-azure/azure:v8.0
      metricsBridge: quay.io/openshift-on-azure/azure:v8.0
      startup: quay.io/openshift-on-azure/azure:v8.0
      sync: quay.io/openshift-on-azure/azure:v8.0
      tlsProxy: quay.io/openshift-on-azure/azure:v8.0
      logAnalyticsAgent: mcr.microsoft.com/azuremonitor/containerinsights/ciprod:ciprod07092019
  v9.0:
    imageOffer: osa
    imagePublisher: redhat
    imageSku: osa_311
    imageVersion: 311.129.20190810
    images:
      alertManager: registry.access.redhat.com/openshift3/prometheus-alertmanager:v3.11.141
      ansibleServiceBroker: registry.access.redhat.com/openshift3/ose-ansible-service-broker:v3.11.141
      clusterMonitoringOperator: registry.access.redhat.com/openshift3/ose-cluster-monitoring-operator:v3.11.141
      configReloader: registry.access.redhat.com/openshift3/ose-configmap-reloader:v3.11.141
      console: registry.access.redhat.com/openshift3/ose-console:v3.11.141
      controlPlane: registry.access.redhat.com/openshift3/ose-control-plane:v3.11.141
      grafana: registry.access.redhat.com/openshift3/grafana:v3.11.141
      kubeRbacProxy: registry.access.redhat.com/openshift3/ose-kube-rbac-proxy:v3.11.141
      kubeStateMetrics: registry.access.redhat.com/openshift3/ose-kube-state-metrics:v3.11.141
      node: registry.access.redhat.com/openshift3/ose-node:v3.11.141
      nodeExporter: registry.access.redhat.com/openshift3/prometheus-node-exporter:v3.11.141
      oAuthProxy: registry.access.redhat.com/openshift3/oauth-proxy:v3.11.141
      prometheus: registry.access.redhat.com/openshift3/prometheus:v3.11.141
      prometheusConfigReloader: registry.access.redhat.com/openshift3/ose-prometheus-config-reloader:v3.11.141
      prometheusOperator: registry.access.redhat.com/openshift3/ose-prometheus-operator:v3.11.141
      registry: registry.access.redhat.com/openshift3/ose-docker-registry:v3.11.141
      registryConsole: registry.access.redhat.com/openshift3/registry-console:v3.11.141
      router: registry.access.redhat.com/openshift3/ose-haproxy-router:v3.11.141
      serviceCatalog: registry.access.redhat.com/openshift3/ose-service-catalog:v3.11.141
      templateServiceBroker: registry.access.redhat.com/openshift3/ose-template-service-broker:v3.11.141
      webConsole: registry.access.redhat.com/openshift3/ose-web-console:v3.11.141
      format: registry.access.redhat.com/openshift3/ose-${component}:v3.11.141
      httpd: registry.access.redhat.com/rhscl/httpd-24-rhel7:2.4-103
      masterEtcd: registry.access.redhat.com/rhel7/etcd:3.2.26-16
      genevaLogging: osarpint.azurecr.io/acs/mdsd:master.20190228.1
      genevaStatsd: osarpint.azurecr.io/acs/mdm:git-a909a2e76
      genevaTDAgent: osarpint.azurecr.io/acs/td-agent:master.20190228.1
      azureControllers: quay.io/openshift-on-azure/azure:latest
      canary: quay.io/openshift-on-azure/azure:latest
      etcdBackup: quay.io/openshift-on-azure/azure:latest
      metricsBridge: quay.io/openshift-on-azure/azure:latest
      startup: quay.io/openshift-on-azure/azure:latest
      sync: quay.io/openshift-on-azure/azure:latest
      tlsProxy: quay.io/openshift-on-azure/azure:latest
      logAnalyticsAgent: mcr.microsoft.com/azuremonitor/containerinsights/ciprod:ciprod07092019
## certificates, used to authenticate to external systems
## Red Hat CDN client certificates
  #packageRepository:
  #  key: <Red Hat CDN client key value. Format: Base64 in YAML, rsa.PrivateKey in struct>
  #  cert: <Red Hat CDN client certificate Format: Base64 in YAML, x509.Certificate struct>
## Geneva integration certificates. Example:
#certificates:
  #genevaLogging:
  #  key: <Geneva logging key value. Format: Base64 in YAML, rsa.PrivateKey in struct>
  #  cert: <Geneva logging certificate Format: Base64 in YAML, x509.Certificate struct>
  #genevaMetrics:
  #  key: <Geneva metrics key value. Base64 in YAML, rsa.PrivateKey in struct>
  #  cert: <Geneva metrics certificate value. Format: Base64 in YAML, x509.Certificate struct>
## Geneva integration other details
genevaLoggingSector: US-Test
genevaLoggingAccount: ccpopenshiftdiag
genevaLoggingNamespace: CCPOpenShift
genevaLoggingControlPlaneAccount: RPOpenShiftAccount
genevaLoggingControlPlaneEnvironment: Test
genevaLoggingControlPlaneRegion: eastus
genevaMetricsAccount: RPOpenShift
genevaMetricsEndpoint: https://az-int.metrics.nsatc.net/
## Container images used for specific OSA Cluster version
## Geneva image pull secret is used to access private component images. Format: base64 encoded .docker/config.json file "{auths:{osarpint.azurecr.io:{username:username,password:notthepasswordyouarelookingfor,email:openshift@example.com,auth:dXNlcm5hbWU6bm90dGhlcGFzc3dvcmR5b3VhcmVsb29raW5nZm9yCg==}}}"
#genevaImagePullSecret: <base64 string of .docker/config.json file>
## Image pull secret is used to pull images from private registries, used system-wide
#imagePullSecret: <base64 string of /var/lib/origin/.docker/config.json file>
